model_type: qdt
prior_n_layer: 3
n_layer: 4
prior_embed_dim: 128
embed_dim: 256
n_head: 4
activation_function: relu
dropout: 0.1
value_penalty: false
policy_penalty: true
behavior_ckpt_file: ???
stochastic_policy: true
fixed_std: true